require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RecordingsController do

  # This should return the minimal set of attributes required to create a valid
  # Recording. As you add validations to Recording, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    script = stub_model Script, :id => 5
    {
      :gender => 'Male',
      :locale => 'Northern Ireland',
      :soundfile => File.new(Rails.root + 'spec/fixtures/ballsdeep.wav'),
      :script => script
    }
  end

  describe "GET index" do
    it "assigns all recordings as @recordings" do
      recording = Recording.create! valid_attributes
      get :index
      assigns(:recordings).should eq([recording])
    end
  end

  describe "GET show" do
    it "assigns the requested recording as @recording" do
      recording = Recording.create! valid_attributes
      get :show, :id => recording.id.to_s
      assigns(:recording).should eq(recording)
    end
  end

  describe "GET new" do
    it "assigns a new recording as @recording" do
      get :new
      assigns(:recording).should be_a_new(Recording)
    end

    it "assigns a random recording as @script" do
      script = Script.new(:body => "Script body...")
      Script.stub(:random) { script }
      get :new
      assigns(:script).should be_a(Script)
    end
  end

  describe "GET edit" do
    it "assigns the requested recording as @recording" do
      recording = Recording.create! valid_attributes
      get :edit, :id => recording.id.to_s
      assigns(:recording).should eq(recording)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Recording" do
        expect {
          post :create, :recording => valid_attributes
        }.to change(Recording, :count).by(1)
      end

      it "assigns a newly created recording as @recording" do
        post :create, :recording => valid_attributes
        assigns(:recording).should be_a(Recording)
        assigns(:recording).should be_persisted
      end

      it "redirects to the created recording" do
        post :create, :recording => valid_attributes
        response.should redirect_to(Recording.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recording as @recording" do
        # Trigger the behavior that occurs when invalid params are submitted
        Recording.any_instance.stub(:save).and_return(false)
        post :create, :recording => {} 
        assigns(:recording).should be_a_new(Recording)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Recording.any_instance.stub(:save).and_return(false)
        post :create, :recording => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested recording" do
        recording = Recording.create! valid_attributes
        # Assuming there are no other recordings in the database, this
        # specifies that the Recording created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Recording.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => recording.id, :recording => {'these' => 'params'}
      end

      it "assigns the requested recording as @recording" do
        recording = Recording.create! valid_attributes
        put :update, :id => recording.id, :recording => valid_attributes
        assigns(:recording).should eq(recording)
      end

      it "redirects to the recording" do
        recording = Recording.create! valid_attributes
        put :update, :id => recording.id, :recording => valid_attributes
        response.should redirect_to(recording)
      end
    end

    describe "with invalid params" do
      it "assigns the recording as @recording" do
        recording = Recording.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Recording.any_instance.stub(:save).and_return(false)
        put :update, :id => recording.id.to_s, :recording => {}
        assigns(:recording).should eq(recording)
      end

      it "re-renders the 'edit' template" do
        recording = Recording.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Recording.any_instance.stub(:save).and_return(false)
        put :update, :id => recording.id.to_s, :recording => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recording" do
      recording = Recording.create! valid_attributes
      expect {
        delete :destroy, :id => recording.id.to_s
      }.to change(Recording, :count).by(-1)
    end

    it "redirects to the recordings list" do
      recording = Recording.create! valid_attributes
      delete :destroy, :id => recording.id.to_s
      response.should redirect_to(recordings_url)
    end
  end

end
